### ISSUE TITLE
Trying to get this working with varnish 4.1.4 and centos 7

### ISSUE THREAD

**Issue by hwatts** [julp/libvmod-keystore#1]
I'm able to get this to build with centos 7 ok using cmake (2.8.12.2) and the hiredis driver without errors:

```
cmake .
STATIC_DRIVERS = redis
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/libvmod-keystore
```

```
make
[ 25%] Built target redis
[100%] Built target keystore
```

```
make install
[ 25%] Built target redis
[100%] Built target keystore
Install the project...
-- Install configuration: ""
-- Installing: /usr/lib64/varnish/vmods/libvmod_keystore.so
-- Removed runtime path from "/usr/lib64/varnish/vmods/libvmod_keystore.so"
```

Which appears to work, but varnish won't start with:

`dlerror: libhiredis.so.0.13: cannot open shared object file: No such file or directory`

Running ldd, it appears that the library is not embedded, but the docs suggest it should be:

```
ldd /usr/lib64/varnish/vmods/libvmod_keystore.so
	linux-vdso.so.1 =>  (0x00007ffe1b7d4000)
	libhiredis.so.0.13 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007ff8b5c70000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff8b6242000)
```

Any ideas?

**Comment by julp** [comment]
Hi,

Is it a reinstallation/recompilation?

What's the output of the following commands:
1. `grep HIREDIS_LIBRARIES CMakeCache.txt`
2. `realpath /usr/lib64/varnish/vmods/libvmod_keystore.so`

Thanks.

**Comment by hwatts** [comment]
Hi,

Apologies, yes, the outputs above are after a few attempts. outputs of those commands below:

```
grep HIREDIS_LIBRARIES CMakeCache.txt
HIREDIS_LIBRARIES:FILEPATH=/usr/local/lib/libhiredis.so
//ADVANCED property for variable: HIREDIS_LIBRARIES
HIREDIS_LIBRARIES-ADVANCED:INTERNAL=1
```

```
realpath /usr/lib64/varnish/vmods/libvmod_keystore.so
/usr/lib64/varnish/vmods/libvmod_keystore.so
```

However, I have got a bit further in the last few hours. I was building hiredis from source, but inspected what the hiredis rpm in the epel repo did and was able to get it to work by copying the built libhiredis.so.0.13 from /usr/local/lib/libhiredis.so.0.13 to /usr/lib64/libhiredis.so.0.13, which I guess has to do with the default library paths on centos.

Now I get dlerror: /usr/lib64/varnish/vmods/libvmod_keystore.so: undefined symbol: vmod_key_store_register_driver on starting varnish, which I'm starting to suspect is because of my lack of knowledge about how this should be built.

When i initially ran make, I got the following errors:

```
make
Scanning dependencies of target redis
[ 25%] Building C object drivers/redis/CMakeFiles/redis.dir/src/vmod_keystore_redis.c.o
[ 25%] Built target redis
[ 50%] Generating vcc_if.c, vcc_if.h
WARNING: Unknown keyword: $Init:
WARNING: $Init description is not included in .rst:
[(4, '')]
Scanning dependencies of target keystore
[ 75%] Building C object CMakeFiles/keystore.dir/src/vmod_keystore.c.o
[100%] Building C object CMakeFiles/keystore.dir/vcc_if.c.o
/home/vagrant/libvmod-keystore/vcc_if.c:7:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make[2]: *** [CMakeFiles/keystore.dir/vcc_if.c.o] Error 1
make[1]: *** [CMakeFiles/keystore.dir/all] Error 2
make: *** [all] Error 2
```

I copied config.h from the varnish source dir and make appeared to work after this, but I'm suspecting this isn't the right thing to do. Is this a more fundamental 4.1 compatibility issue?

**Comment by julp** [comment]
Re,

Don't apologize, when I asked if it was a reinstallation/recompilation, it was about cmake may kept some old informations of a previous build in cache.

> I guess has to do with the default library paths on centos

It seems /usr/local/lib is not and is not in /etc/ld.so.conf (neither part of LD_LIBRARY_PATH).

> Is this a more fundamental 4.1 compatibility issue?

This is not really an issue: you can create it empty (`touch config.h`) but, yes, a `#include "config.h"` is "now" (since 4.1.4?) automatically generated in the C code (vcc_if.c) by varnish (vmodtool). So any vmod has "now" to embed or build one.

> Now I get dlerror: /usr/lib64/varnish/vmods/libvmod_keystore.so: undefined symbol: vmod_key_store_register_driver on starting varnish, which I'm starting to suspect is because of my lack of knowledge about how this should be built.

Sorry, my mistake, on registering static drivers, I wrote `vmod_key_store_register_driver` instead of `vmod_keystore_register_driver`. I missed it using dynamic drivers. It should be fixed by last commits.

---

Note that [a far more complete redis vmod](https://github.com/carlosabalde/libvmod-redis) exists, this one is more a concept (on replacing autotools by CMake and in a modular approach with static or dynamic "submodules").

**Comment by hwatts** [comment]
Great, it's building fine now. I had seen the other redis vmod but liked the idea of the higher level get/set/exists methods. However, it does seem to have a reasonable number of people using it in the wild, so I'll have a play with both. Thanks for all the help!
